version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grex_finances
      MYSQL_USER: grex_user
      MYSQL_PASSWORD: grex_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - grex-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: grex_finances
      JWT_SECRET: development-jwt-secret-change-in-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mysql
    networks:
      - grex-network
    volumes:
      - .:/app
      - /app/node_modules

  # phpMyAdmin (opcional, para gerenciar o banco)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - grex-network

volumes:
  mysql_data:

networks:
  grex-network:
    driver: bridge
